# -*- coding: utf-8 -*-
"""02_Numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LZwLzlVCUNJZhQKi3aCwpx4rGsPtR82l
"""

base = 10.5
height = 7

type(base)

area = 1 / 2 * base * height
area

type(area)

10/3

10//3

17 % 3

3**2

10 + 2 * 3

(10 + 2) * 3

foo = 2.3e4
foo

bar = 2.3e-3
bar

food = 120.34
rent = 500.8
utilities = 200.5

total = food + rent + utilities
total

round(total)

income = 10000
expenses = 9000
savings = income - expenses
savings

food = "120.34"
rent = "500.8"
utilities = "200.5"

total = food + rent + utilities
total

format(5, 'b')

